<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Contracts\Database\Query\Expression;
use Illuminate\Support\Facades\DB;

/**
 * ValidatedSqlExpression - A value object representing a validated SQL expression
 *
 * V40-SQL-SECURITY: Validated SQL Expression Wrapper
 * ===================================================
 * This class wraps SQL expressions that have been validated against SQL injection.
 * It provides type safety and makes the security intention explicit in the code.
 *
 * Usage:
 *   - Create instances only from trusted sources (StockService, DatabaseCompatibilityService)
 *   - The validation must happen BEFORE creating this object
 *   - Implements Stringable for convenient use in raw SQL contexts
 *
 * Security Guarantee:
 *   By using this class, you are asserting that the SQL expression has been:
 *   1. Generated from hardcoded patterns with validated identifiers
 *   2. NOT derived from user input
 *   3. Validated using appropriate regex patterns
 *
 * @see \App\Services\StockService for stock calculation expressions
 * @see \App\Services\DatabaseCompatibilityService for date/time expressions
 */
final class ValidatedSqlExpression implements \Stringable
{
    /**
     * @param  string  $expression  The validated SQL expression
     */
    private function __construct(
        private readonly string $expression
    ) {}

    /**
     * Create a validated SQL expression from StockService.
     *
     * @param  string  $expression  Expression generated by StockService methods
     * @return static
     */
    public static function fromStockService(string $expression): self
    {
        // The validation is done in StockService before generating the expression
        // This method just provides type clarity
        return new self($expression);
    }

    /**
     * Create a validated SQL expression from DatabaseCompatibilityService.
     *
     * @param  string  $expression  Expression generated by DatabaseCompatibilityService methods
     * @return static
     */
    public static function fromDatabaseCompatibilityService(string $expression): self
    {
        // The validation is done in DatabaseCompatibilityService before generating the expression
        // This method just provides type clarity
        return new self($expression);
    }

    /**
     * Create a validated SQL expression from a hardcoded pattern.
     * Use this only for expressions that are entirely hardcoded in the codebase.
     *
     * @param  string  $expression  A hardcoded SQL expression (no variables)
     * @return static
     */
    public static function fromHardcoded(string $expression): self
    {
        return new self($expression);
    }

    /**
     * Get the SQL expression string.
     */
    public function toString(): string
    {
        return $this->expression;
    }

    /**
     * Get as Laravel DB::raw expression.
     */
    public function toDbRaw(): Expression
    {
        return DB::raw($this->expression);
    }

    /**
     * Implements Stringable for convenient use in raw SQL contexts.
     */
    public function __toString(): string
    {
        return $this->expression;
    }
}
